import { CarModel } from './car.model';

export const data: CarModel[] = [
  {
    brand: 'Nissan',
    model: 'NV2500',
    year: 2012,
    country: 'Russia',
    damaged: true,
    color: '#ab4e61',
  },
  {
    brand: 'Pontiac',
    model: 'Trans Sport',
    year: 1991,
    country: 'Germany',
    damaged: true,
    color: '#a4762b',
  },
  {
    brand: 'GMC',
    model: 'Yukon XL 2500',
    year: 2007,
    country: 'Philippines',
    damaged: true,
    color: '#364bab',
  },
  {
    brand: 'Pontiac',
    model: 'Sunbird',
    year: 1993,
    country: 'Brazil',
    damaged: false,
    color: '#d8877d',
  },
  {
    brand: 'Ford',
    model: 'Fusion',
    year: 2009,
    country: 'Indonesia',
    damaged: true,
    color: '#31be7b',
  },
  {
    brand: 'Ford',
    model: 'Explorer',
    year: 2007,
    country: 'Brazil',
    damaged: false,
    color: '#ffbb6a',
  },
  {
    brand: 'Buick',
    model: 'Rendezvous',
    year: 2003,
    country: 'Argentina',
    damaged: false,
    color: '#0338a3',
  },
  {
    brand: 'Mazda',
    model: 'Miata MX-5',
    year: 2002,
    country: 'Russia',
    damaged: false,
    color: '#4a9f3e',
  },
  {
    brand: 'Ford',
    model: 'Taurus',
    year: 1987,
    country: 'Croatia',
    damaged: false,
    color: '#9c7e06',
  },
  {
    brand: 'Infiniti',
    model: 'G35',
    year: 2007,
    country: 'Brazil',
    damaged: true,
    color: '#07ed49',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'CLK-Class',
    year: 2004,
    country: 'Poland',
    damaged: false,
    color: '#30a40f',
  },
  {
    brand: 'Toyota',
    model: 'Yaris',
    year: 2008,
    country: 'Indonesia',
    damaged: true,
    color: '#2ce77d',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'SLK-Class',
    year: 2011,
    country: 'Brazil',
    damaged: false,
    color: '#b57440',
  },
  {
    brand: 'Plymouth',
    model: 'Voyager',
    year: 1995,
    country: 'China',
    damaged: true,
    color: '#63f748',
  },
  {
    brand: 'Audi',
    model: 'S8',
    year: 2006,
    country: 'Russia',
    damaged: false,
    color: '#8c276f',
  },
  {
    brand: 'Lincoln',
    model: 'Navigator',
    year: 2009,
    country: 'Indonesia',
    damaged: true,
    color: '#0928ec',
  },
  {
    brand: 'Buick',
    model: 'Park Avenue',
    year: 1994,
    country: 'China',
    damaged: true,
    color: '#207a17',
  },
  {
    brand: 'Maserati',
    model: 'Quattroporte',
    year: 2012,
    country: 'Belarus',
    damaged: false,
    color: '#ef976f',
  },
  {
    brand: 'Toyota',
    model: 'RAV4',
    year: 2002,
    country: 'Poland',
    damaged: false,
    color: '#93df98',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2010,
    country: 'Serbia',
    damaged: false,
    color: '#fe9a9a',
  },
  {
    brand: 'Mazda',
    model: 'CX-7',
    year: 2007,
    country: 'Croatia',
    damaged: false,
    color: '#86d9b9',
  },
  {
    brand: 'Suzuki',
    model: 'SJ',
    year: 1989,
    country: 'Indonesia',
    damaged: false,
    color: '#b03a48',
  },
  {
    brand: 'Chevrolet',
    model: 'S10 Blazer',
    year: 1994,
    country: 'China',
    damaged: false,
    color: '#0d4f45',
  },
  {
    brand: 'Lexus',
    model: 'GX',
    year: 2005,
    country: 'Portugal',
    damaged: false,
    color: '#3204f9',
  },
  {
    brand: 'Chevrolet',
    model: 'Corvette',
    year: 1997,
    country: 'China',
    damaged: true,
    color: '#b45841',
  },
  {
    brand: 'Chevrolet',
    model: 'Corvette',
    year: 1989,
    country: 'Brazil',
    damaged: true,
    color: '#9639aa',
  },
  {
    brand: 'Pontiac',
    model: 'Montana',
    year: 2005,
    country: 'China',
    damaged: false,
    color: '#544410',
  },
  {
    brand: 'Mazda',
    model: 'Mazda3',
    year: 2005,
    country: 'Indonesia',
    damaged: false,
    color: '#1b840c',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'G-Class',
    year: 2009,
    country: 'Philippines',
    damaged: true,
    color: '#a2453f',
  },
  {
    brand: 'Scion',
    model: 'tC',
    year: 2009,
    country: 'Japan',
    damaged: true,
    color: '#e97597',
  },
  {
    brand: 'Honda',
    model: 'CR-V',
    year: 2012,
    country: 'Brazil',
    damaged: false,
    color: '#e2ea18',
  },
  {
    brand: 'Isuzu',
    model: 'Amigo',
    year: 1993,
    country: 'Japan',
    damaged: false,
    color: '#89ab42',
  },
  {
    brand: 'Acura',
    model: 'NSX',
    year: 1992,
    country: 'Philippines',
    damaged: true,
    color: '#444cdd',
  },
  {
    brand: 'Subaru',
    model: 'SVX',
    year: 1994,
    country: 'Portugal',
    damaged: true,
    color: '#fdf2b7',
  },
  {
    brand: 'Suzuki',
    model: 'SX4',
    year: 2012,
    country: 'Portugal',
    damaged: false,
    color: '#773a64',
  },
  {
    brand: 'Ford',
    model: 'F-Series',
    year: 1997,
    country: 'Netherlands',
    damaged: true,
    color: '#12371e',
  },
  {
    brand: 'Pontiac',
    model: 'Firebird',
    year: 1988,
    country: 'Malaysia',
    damaged: true,
    color: '#b6ed4a',
  },
  {
    brand: 'Cadillac',
    model: 'Fleetwood',
    year: 1994,
    country: 'United States',
    damaged: false,
    color: '#2b0a4a',
  },
  {
    brand: 'Pontiac',
    model: 'Grand Prix',
    year: 1971,
    country: 'Mongolia',
    damaged: true,
    color: '#f0cd7f',
  },
  {
    brand: 'Dodge',
    model: 'Aspen',
    year: 1976,
    country: 'China',
    damaged: false,
    color: '#ab7e31',
  },
  {
    brand: 'Mitsubishi',
    model: 'Galant',
    year: 2001,
    country: 'Moldova',
    damaged: true,
    color: '#9f60ce',
  },
  {
    brand: 'Toyota',
    model: 'Venza',
    year: 2011,
    country: 'Indonesia',
    damaged: false,
    color: '#69181e',
  },
  {
    brand: 'Dodge',
    model: 'Ram 3500',
    year: 1995,
    country: 'China',
    damaged: true,
    color: '#3c91f0',
  },
  {
    brand: 'Lexus',
    model: 'GX',
    year: 2005,
    country: 'Dominican Republic',
    damaged: false,
    color: '#d6efd5',
  },
  {
    brand: 'Jaguar',
    model: 'XK Series',
    year: 2001,
    country: 'Ukraine',
    damaged: true,
    color: '#1aaf79',
  },
  {
    brand: 'Mitsubishi',
    model: 'Mirage',
    year: 1995,
    country: 'Indonesia',
    damaged: false,
    color: '#b54efa',
  },
  {
    brand: 'GMC',
    model: 'Sierra 1500',
    year: 2001,
    country: 'Indonesia',
    damaged: true,
    color: '#29257d',
  },
  {
    brand: 'Jeep',
    model: 'Liberty',
    year: 2008,
    country: 'China',
    damaged: true,
    color: '#ce03b0',
  },
  {
    brand: 'BMW',
    model: '7 Series',
    year: 2012,
    country: 'Burkina Faso',
    damaged: true,
    color: '#9f5ad7',
  },
  {
    brand: 'Nissan',
    model: 'Quest',
    year: 2007,
    country: 'Russia',
    damaged: false,
    color: '#ce9ca5',
  },
  {
    brand: 'Maybach',
    model: 'Landaulet',
    year: 2011,
    country: 'Bulgaria',
    damaged: false,
    color: '#631df4',
  },
  {
    brand: 'Cadillac',
    model: 'Seville',
    year: 2004,
    country: 'Mexico',
    damaged: true,
    color: '#fb8af5',
  },
  {
    brand: 'Pontiac',
    model: 'Grand Prix',
    year: 1979,
    country: 'Russia',
    damaged: true,
    color: '#1992d9',
  },
  {
    brand: 'BMW',
    model: '3 Series',
    year: 1999,
    country: 'Indonesia',
    damaged: false,
    color: '#8f6536',
  },
  {
    brand: 'Chevrolet',
    model: 'Monte Carlo',
    year: 1996,
    country: 'Armenia',
    damaged: false,
    color: '#3ec84f',
  },
  {
    brand: 'Aston Martin',
    model: 'Vantage',
    year: 2010,
    country: 'China',
    damaged: false,
    color: '#baf6fc',
  },
  {
    brand: 'Audi',
    model: 'S5',
    year: 2010,
    country: 'Russia',
    damaged: false,
    color: '#a799dc',
  },
  {
    brand: 'Lincoln',
    model: 'MKX',
    year: 2011,
    country: 'Indonesia',
    damaged: true,
    color: '#fc734b',
  },
  {
    brand: 'Volkswagen',
    model: 'Quantum',
    year: 1984,
    country: 'Nigeria',
    damaged: true,
    color: '#f81de7',
  },
  {
    brand: 'Cadillac',
    model: 'XLR',
    year: 2005,
    country: 'China',
    damaged: true,
    color: '#096dab',
  },
  {
    brand: 'Mercury',
    model: 'Sable',
    year: 1995,
    country: 'Russia',
    damaged: false,
    color: '#16bbbe',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    year: 1997,
    country: 'Greece',
    damaged: true,
    color: '#32d68e',
  },
  {
    brand: 'Ford',
    model: 'Mustang',
    year: 1995,
    country: 'Poland',
    damaged: true,
    color: '#0332da',
  },
  {
    brand: 'Mazda',
    model: 'CX-5',
    year: 2013,
    country: 'Sweden',
    damaged: true,
    color: '#47b08a',
  },
  {
    brand: 'Ford',
    model: 'Mustang',
    year: 1989,
    country: 'China',
    damaged: true,
    color: '#64fe30',
  },
  {
    brand: 'Ford',
    model: 'E350',
    year: 2004,
    country: 'Ireland',
    damaged: true,
    color: '#339ab2',
  },
  {
    brand: 'Honda',
    model: 'Civic Si',
    year: 2003,
    country: 'United States',
    damaged: true,
    color: '#95e6f5',
  },
  {
    brand: 'Cadillac',
    model: 'Allante',
    year: 1992,
    country: 'China',
    damaged: false,
    color: '#29c1b4',
  },
  {
    brand: 'Chrysler',
    model: 'Prowler',
    year: 2002,
    country: 'Peru',
    damaged: false,
    color: '#eefb32',
  },
  {
    brand: 'Mercury',
    model: 'Mountaineer',
    year: 2004,
    country: 'China',
    damaged: true,
    color: '#667b00',
  },
  {
    brand: 'Ford',
    model: 'E350',
    year: 2012,
    country: 'Guatemala',
    damaged: false,
    color: '#cf70b6',
  },
  {
    brand: 'Dodge',
    model: 'Dakota',
    year: 2008,
    country: 'Tunisia',
    damaged: false,
    color: '#3fa61d',
  },
  {
    brand: 'Studebaker',
    model: 'Avanti',
    year: 1962,
    country: 'Portugal',
    damaged: true,
    color: '#c75847',
  },
  {
    brand: 'Lincoln',
    model: 'Navigator L',
    year: 2010,
    country: 'Cape Verde',
    damaged: true,
    color: '#52d0fa',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'SL-Class',
    year: 2011,
    country: 'Colombia',
    damaged: true,
    color: '#334b92',
  },
  {
    brand: 'Plymouth',
    model: 'Colt Vista',
    year: 1993,
    country: 'South Africa',
    damaged: true,
    color: '#628d89',
  },
  {
    brand: 'Infiniti',
    model: 'Q',
    year: 1998,
    country: 'Indonesia',
    damaged: false,
    color: '#267aa1',
  },
  {
    brand: 'Ford',
    model: 'Expedition',
    year: 1999,
    country: 'Jamaica',
    damaged: true,
    color: '#270fa0',
  },
  {
    brand: 'Dodge',
    model: 'Grand Caravan',
    year: 2011,
    country: 'Russia',
    damaged: true,
    color: '#558c72',
  },
  {
    brand: 'Mitsubishi',
    model: 'Diamante',
    year: 1997,
    country: 'China',
    damaged: false,
    color: '#1c876a',
  },
  {
    brand: 'Maserati',
    model: 'Spyder',
    year: 2004,
    country: 'Peru',
    damaged: false,
    color: '#541bd9',
  },
  {
    brand: 'Toyota',
    model: 'Tacoma',
    year: 2000,
    country: 'China',
    damaged: false,
    color: '#e82916',
  },
  {
    brand: 'Suzuki',
    model: 'Swift',
    year: 1988,
    country: 'Indonesia',
    damaged: false,
    color: '#3c9704',
  },
  {
    brand: 'Mitsubishi',
    model: 'Mirage',
    year: 1994,
    country: 'China',
    damaged: true,
    color: '#e32de7',
  },
  {
    brand: 'Volvo',
    model: '850',
    year: 1997,
    country: 'Indonesia',
    damaged: false,
    color: '#d48539',
  },
  {
    brand: 'Maserati',
    model: '228',
    year: 1989,
    country: 'Colombia',
    damaged: false,
    color: '#8d3262',
  },
  {
    brand: 'Chevrolet',
    model: 'Corvette',
    year: 1956,
    country: 'Malaysia',
    damaged: true,
    color: '#503d74',
  },
  {
    brand: 'Chevrolet',
    model: 'Silverado 2500',
    year: 2007,
    country: 'Guatemala',
    damaged: false,
    color: '#af41d5',
  },
  {
    brand: 'Mazda',
    model: 'B-Series',
    year: 1994,
    country: 'China',
    damaged: true,
    color: '#6a4ae2',
  },
  {
    brand: 'Audi',
    model: 'RS 4',
    year: 2007,
    country: 'Portugal',
    damaged: true,
    color: '#4bdad1',
  },
  {
    brand: 'Dodge',
    model: 'Intrepid',
    year: 1993,
    country: 'Greece',
    damaged: true,
    color: '#157516',
  },
  {
    brand: 'Land Rover',
    model: 'Range Rover',
    year: 2004,
    country: 'Canada',
    damaged: false,
    color: '#670c32',
  },
  {
    brand: 'Lotus',
    model: 'Esprit',
    year: 2003,
    country: 'Canada',
    damaged: false,
    color: '#18f77b',
  },
  {
    brand: 'Mazda',
    model: 'Protege5',
    year: 2002,
    country: 'Russia',
    damaged: false,
    color: '#17a9da',
  },
  {
    brand: 'Acura',
    model: 'NSX',
    year: 1996,
    country: 'Malta',
    damaged: true,
    color: '#50883f',
  },
  {
    brand: 'Pontiac',
    model: 'Montana',
    year: 2006,
    country: 'Portugal',
    damaged: false,
    color: '#6c232a',
  },
  {
    brand: 'BMW',
    model: 'X5',
    year: 2005,
    country: 'China',
    damaged: true,
    color: '#c6b564',
  },
  {
    brand: 'Saturn',
    model: 'Outlook',
    year: 2008,
    country: 'Tunisia',
    damaged: true,
    color: '#5531b3',
  },
  {
    brand: 'Aston Martin',
    model: 'DB9',
    year: 2009,
    country: 'Kazakhstan',
    damaged: false,
    color: '#2cb0af',
  },
  {
    brand: 'Cadillac',
    model: 'XLR',
    year: 2004,
    country: 'Venezuela',
    damaged: false,
    color: '#273b45',
  },
];
